version: '3.9'
services:
  vehicle-service-db:
    image: postgres:16.1
    container_name: vehicle-service-db
    environment:
      POSTGRES_DB: vehicle-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - micronaut-course-network
  store-service-cache:
    image: redis:alpine
    container_name: store-service-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - micronaut-course-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - '2182:2181'
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: '-Dzookeeper.4lw.commands.whitelist=ruok'
    networks:
      - micronaut-course-network
  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker
    hostname: kafka-broker
    restart: always
    ports:
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,LISTENER_LOCAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_COMPRESSION_TYPE: producer
    networks:
      - micronaut-course-network
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - '9000:9000'
    environment:
      ZK_HOSTS: 'zookeeper:2181'
    networks:
      - micronaut-course-network
  report-service-db:
    image: mongo:7.0
    container_name: report-service-db
    hostname: report-service-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    networks:
      - micronaut-course-network
networks:
  micronaut-course-network:
    name: micronaut-course-network
    driver: bridge
